#!/usr/bin/env bash

set -ueo pipefail

ASDF_BIN="${ASDF_DIR:-$HOME/.asdf}/bin/"
ASDF_INSTALL_BIN_PATH="$(dirname $("${ASDF_BIN}/asdf" which nim))"

regenerate() {
  # After a nimble operation, regenerate nim shims to find new package binaries
  if "${ASDF_BIN}/asdf" reshim nim; then
    echo "  asdf-nim: regenerated shims"
  else
    echo "  asdf-nim: failed to regenerate shims"
    exit 1
  fi
  echo
}

trap 'trap - HUP; SIGNAL=SIGHUP; regenerate; kill -HUP $$' HUP
trap 'trap - INT; SIGNAL=SIGINT; regenerate; kill -INT $$' INT
trap 'trap - TERM; SIGNAL=SIGTERM; regenerate; kill -TERM $$' TERM

if "${ASDF_INSTALL_BIN_PATH}/nimble" "$@"; then
  case "${1:-}" in
    install | develop | uninstall)
      regenerate
      ;;
  esac
else
  exit $?
fi
