#!/usr/bin/env bash

set -ueo pipefail

regenerate() {
  # After a nimble operation, regenerate nim shims to find new package binaries
  if "$(command -v asdf)" reshim nim; then
    echo "  asdf-nim: regenerated shims"
  else
    echo "  asdf-nim: failed to regenerate shims"
  fi
  echo
}

trap 'trap - HUP; SIGNAL=SIGHUP; regenerate; kill -HUP $$' HUP
trap 'trap - INT; SIGNAL=SIGINT; regenerate; kill -INT $$' INT
trap 'trap - TERM; SIGNAL=SIGTERM; regenerate; kill -TERM $$' TERM

exit_code=0
"$(dirname "$(asdf which nim)")/nimble" "$@" || exit_code=$?
if [ $exit_code -eq 0 ]; then
  if [ -z "${SIGNAL:-}" ]; then
    case "${1-}" in
      install | develop | uninstall)
        regenerate
        ;;
    esac
  fi
fi
exit $exit_code
