#!/usr/bin/env bash

set -ueo pipefail

# shellcheck source=SCRIPTDIR/../lint/utils.bash
source "$(dirname "${BASH_SOURCE[0]}")/../lint/utils.bash"

while read path; do
  lint "$path" "yes"
done <<<"$(git diff --name-only --staged)"
