#!/usr/bin/env bash

set -ueo pipefail

# shellcheck source=SCRIPTDIR/lib/lint_utils.bash
source "$(dirname "${BASH_SOURCE[0]}")/lib/lint_utils.bash"

while read -r path; do
  lint "$path" "yes"
done <<<"$(find . -type f \( -not -path '*/\.git/*' \) -a \( -not -path "*/node_modules/*" \))"
