name: Build latest nightly
on:
  schedule:
    - cron: "0 0 * * *" # daily at midnight

jobs:
  test:
    name: Test nim-${{ matrix.nim-version }} / ${{ matrix.libc }} / x86_64
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        include:
          # Test installation of official Linux binaries from nim-lang.org
          - os: ubuntu-latest
            nim-version: latest
            libc: linux-glibc

          # Test installation of unofficial macOS binaries from elijahr/nim-builds
          - os: macos-latest
            nim-version: latest
            libc: macOS

    steps:
      - name: Disable tcp/udp offloading
        run: |
          # Prevent network slowness
          # See https://github.com/actions/virtual-environments/issues/1187#issuecomment-696195756
          # and https://github.com/enso-org/enso/pull/1159
          if [ "${{ runner.os }}" == "macOS" ]; then
            sudo sysctl -w net.link.generic.system.hwcksum_tx=0
            sudo sysctl -w net.link.generic.system.hwcksum_rx=0
          else
            sudo ethtool -K eth0 tx off rx off
          fi

      # Optimization: re-use cached Nim->C compilation
      - name: Restore cache
        if: matrix.nim-version != 'ref:HEAD'
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: cache-${{ matrix.os }}-${{ matrix.nim-version }}

      - name: Install asdf
        uses: asdf-vm/actions/setup@v1

      - name: Install asdf-nim & test
        shell: bash
        run: |
          set -ueo pipefail
          mkdir -p asdf-nim
          cd asdf-nim
          git init
          git remote add origin "https://github.com/${GITHUB_REPOSITORY}.git"
          git fetch origin "$GITHUB_SHA" --depth 1
          git reset --hard FETCH_HEAD
          asdf plugin test nim . --asdf-tool-version ${{ matrix.nim-version }}
