# yamllint disable rule:line-length

name: Latest Nim
on:
  pull_request:
    paths:
      - .github/workflows/build-latest-nightly.yml
  push:
    paths:
      - .github/workflows/build-latest-nightly.yml

  schedule:
    # daily at midnight
    - cron: '0 0 * * *'

jobs:
  test:
    name: Test nim-${{ matrix.nim-version }} / ${{ matrix.libc }} / x86_64
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        include:
          # Test installation of official Linux binaries (nim-lang.org)
          - os: ubuntu-latest
            nim-version: latest
            libc: linux-glibc

          # Test installation of unofficial macOS binaries (elijahr/nim-builds)
          - os: macos-latest
            nim-version: latest
            libc: macOS

    steps:
      # Optimization: re-use cached Nim->C compilation
      - name: Restore cache
        if: matrix.nim-version != 'ref:HEAD'
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: cache-${{ matrix.os }}-${{ matrix.nim-version }}

      - name: Install asdf
        uses: asdf-vm/actions/setup@v1

      - name: Install asdf-nim & test
        shell: bash
        run: |
          set -ueo pipefail
          mkdir -p asdf-nim
          cd asdf-nim
          git init
          git remote add origin "https://github.com/${GITHUB_REPOSITORY}.git"
          git fetch origin "$GITHUB_SHA" --depth 1
          git reset --hard FETCH_HEAD
          asdf plugin test nim . --asdf-tool-version "${{ matrix.nim-version }}" --asdf-plugin-gitref "${GITHUB_SHA}" nim -v
