name: Build latest nightly
on:
  schedule:
    - cron: "0 0 * * *" # daily at midnight

jobs:
  test:
    name: Test nim-${{ matrix.nim-version }} / ${{ matrix.libc }} / x86_64
    strategy:
      fail-fast: false
      matrix:
        include:
          # Test installation of official Linux binaries from nim-lang.org
          - os: ubuntu-latest
            nim-version: latest
            libc: linux-glibc

          # Test installation of unofficial macOS binaries from elijahr/nim-builds
          - os: macos-latest
            nim-version: latest
            libc: macOS

    runs-on: ${{ matrix.os }}
    steps:
      # Prevent network slowness
      # See https://github.com/actions/virtual-environments/issues/1187#issuecomment-696195756
      # and https://github.com/enso-org/enso/pull/1159
      - name: Disable TCP/UDP Offloading (macOS)
        if: runner.os == 'macOS'
        run: |
          sudo sysctl -w net.link.generic.system.hwcksum_tx=0
          sudo sysctl -w net.link.generic.system.hwcksum_rx=0
      - name: Disable TCP/UDP Offloading (Linux)
        if: runner.os == 'Linux'
        run: sudo ethtool -K eth0 tx off rx off
      - name: Disable TCP/UDP Offloading (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: >
          Disable-NetAdapterChecksumOffload -Name * -TcpIPv4 -UdpIPv4 -TcpIPv6
          -UdpIPv6

      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: nim -v
          version: ${{ matrix.nim-version }}
