name: Lint
on:
  pull_request:
    brances: ["*"]
  push:
    brances: ["*"]
  schedule:
    - cron: "0 0 * * *" # daily at midnight

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install prettier
      - uses: actions/setup-node@v2
        with:
          node-version: "15"

      - name: Install shfmt
        run: brew install shfmt

      - name: Update Shellcheck
        run: |
          sudo apt install xz-utils
          scversion="stable"
          wget -qO- "https://github.com/koalaman/shellcheck/releases/download/${scversion?}/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv
          sudo cp "shellcheck-${scversion}/shellcheck" /usr/bin/
          shellcheck --version

      - name: check
        run: ./lint/check-all
