name: lint
# yamllint disable rule:truthy
on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]
    tags: ["*"]
# yamllint enable rule:truthy

jobs:
  lint:
    name: lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # This is necessary for linting only recent changes

      - name: Run lintball
        uses: elijahr/run-lintball@v2
        with:
          default-branch: main
