name: Lint
# yamllint disable rule:truthy
on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]
    tags: ["*"]
# yamllint enable rule:truthy

jobs:
  lint:
    name: lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run lintball
        uses: elijahr/lintball@v2
