name: Lint
on:
  pull_request:
    brances: ["*"]
  push:
    brances: ["*"]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "15"

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install deps
        run: ./install.sh --deps

      - name: check
        run: ./bin/lintball .
